"""Email composer — builds professional response emails with deal summaries and attachments."""

import logging
import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.deal import Deal
from app.models.om import OMVersion
from app.models.risk import RiskReport
from app.storage.s3 import download_document

logger = logging.getLogger(__name__)


async def gather_deliverables(db: AsyncSession, deal_id: uuid.UUID) -> list[dict]:
    """Collect the latest deliverables (OM PDF, Risk Report PDF, Excel) for email attachment.

    Returns list of {filename, data (bytes), mime_type}.
    """
    attachments = []

    # Get deal for naming
    deal_result = await db.execute(select(Deal).where(Deal.id == deal_id))
    deal = deal_result.scalar_one_or_none()
    deal_name = (deal.property_name or "Deal").replace(" ", "_")

    # Latest OM PDF
    om_result = await db.execute(
        select(OMVersion)
        .where(OMVersion.deal_id == deal_id, OMVersion.status == "ready")
        .order_by(OMVersion.version_number.desc())
        .limit(1)
    )
    om = om_result.scalar_one_or_none()
    if om and om.s3_key:
        try:
            om_bytes = download_document(om.s3_key)
            attachments.append({
                "filename": f"{deal_name}_Offering_Memorandum_v{om.version_number}.pdf",
                "data": om_bytes,
                "mime_type": "application/pdf",
            })
        except Exception as e:
            logger.warning("Failed to download OM PDF for deal %s: %s", deal_id, e)

    # Latest Risk Report PDF
    risk_result = await db.execute(
        select(RiskReport)
        .where(RiskReport.deal_id == deal_id, RiskReport.status == "ready")
        .order_by(RiskReport.version_number.desc())
        .limit(1)
    )
    risk = risk_result.scalar_one_or_none()
    if risk and risk.s3_key:
        try:
            risk_bytes = download_document(risk.s3_key)
            attachments.append({
                "filename": f"{deal_name}_Risk_Assessment_v{risk.version_number}.pdf",
                "data": risk_bytes,
                "mime_type": "application/pdf",
            })
        except Exception as e:
            logger.warning("Failed to download Risk Report for deal %s: %s", deal_id, e)

    # Excel financial model
    excel_key = f"deals/{deal_id}/financial/model.xlsx"
    try:
        excel_bytes = download_document(excel_key)
        attachments.append({
            "filename": f"{deal_name}_Financial_Model.xlsx",
            "data": excel_bytes,
            "mime_type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        })
    except Exception as e:
        logger.debug("No Excel model found for deal %s: %s", deal_id, e)

    return attachments


def build_response_html(
    sender_name: str,
    deal_name: str,
    summary_text: str,
    attachments_included: list[str],
) -> str:
    """Build the HTML body for a deal analysis response email."""
    attachment_list = "".join(f"<li>{name}</li>" for name in attachments_included)

    return f"""\
<div style="font-family: 'Inter', Arial, sans-serif; color: #1a1a1a; max-width: 680px;">
  <p>Hi {sender_name or "there"},</p>

  <p>We've completed our analysis of <strong>{deal_name}</strong>. Here's a summary of our findings:</p>

  <div style="background: #f8f9fa; border-left: 4px solid #2563eb; padding: 16px 20px; margin: 20px 0; border-radius: 0 8px 8px 0;">
    {summary_text}
  </div>

  <p><strong>Attached deliverables:</strong></p>
  <ul style="line-height: 1.8;">
    {attachment_list}
  </ul>

  <p>Please review and let us know if you'd like us to adjust any assumptions, explore alternative scenarios, or dig deeper into any aspect of the deal.</p>

  <p style="color: #6b7280; font-size: 13px; margin-top: 32px; border-top: 1px solid #e5e7eb; padding-top: 16px;">
    This analysis was generated by Plumb AI. All data has been extracted from your submitted documents
    and enriched with NYC public records (ACRIS, DOB, ZoLa). Every figure traces back to a source document.
  </p>

  <p>Best,<br><strong>Plumb</strong></p>
</div>
"""


def build_followup_response_html(
    sender_name: str,
    deal_name: str,
    response_text: str,
    changes_made: list[str],
    attachments_included: list[str],
) -> str:
    """Build the HTML body for a follow-up response email."""
    changes_list = "".join(f"<li>{change}</li>" for change in changes_made)
    attachment_list = "".join(f"<li>{name}</li>" for name in attachments_included)

    return f"""\
<div style="font-family: 'Inter', Arial, sans-serif; color: #1a1a1a; max-width: 680px;">
  <p>Hi {sender_name or "there"},</p>

  <p>We've updated the analysis for <strong>{deal_name}</strong> based on your feedback.</p>

  <div style="background: #f8f9fa; border-left: 4px solid #2563eb; padding: 16px 20px; margin: 20px 0; border-radius: 0 8px 8px 0;">
    {response_text}
  </div>

  <p><strong>Changes made:</strong></p>
  <ul style="line-height: 1.8;">
    {changes_list}
  </ul>

  <p><strong>Updated deliverables attached:</strong></p>
  <ul style="line-height: 1.8;">
    {attachment_list}
  </ul>

  <p>Let us know if you'd like further adjustments.</p>

  <p>Best,<br><strong>Plumb</strong></p>
</div>
"""
