"""Pydantic models for the OM generation system."""

from pydantic import BaseModel


class OMPageSpec(BaseModel):
    """Specification for a single OM page in the manifest."""

    template_name: str  # e.g. "cover", "section_divider"
    section_label: str | None = None  # e.g. "EXECUTIVE SUMMARY"
    page_title: str | None = None  # e.g. "TRANSACTION OVERVIEW"
    context_key: str | None = None  # key in OMContext to check for data
    required: bool = True  # if False, skip when data missing


class OMContext(BaseModel):
    """All data needed to render the full OM."""

    deal_id: str
    property_name: str
    property_address: str
    deal_type_label: str = "CONSTRUCTION FINANCING"

    # Financial model (from app.financial.schemas.FinancialModel)
    financial_model: dict

    # Market context
    market_context: dict | None = None

    # Narratives (generated by LLM)
    transaction_overview: list[str] | None = None  # paragraphs
    investment_highlights: list[dict] | None = None  # [{header, body}]
    market_narrative: list[dict] | None = None  # [{header, body}]
    sponsor_bios: dict[str, list[str]] | None = None  # name -> paragraphs

    # Images (from deal_images table)
    hero_image_url: str | None = None
    rendering_images: list[dict] | None = None  # [{url, caption}]
    lot_map_url: str | None = None
    market_images: list[dict] | None = None
    sponsor_data: list[dict] | None = None  # [{name, narrative, logos, projects}]

    # Comps (from market_context)
    rent_comps: list[dict] | None = None
    sales_comps: list[dict] | None = None
    lease_comps: list[dict] | None = None

    # Property stats for development overview
    property_stats: dict | None = None

    # Sponsor info
    sponsors: list[dict] | None = None


class OMVersionCreate(BaseModel):
    """Schema for creating a new OM version record."""

    deal_id: str
    version_number: int
    s3_key: str
    html_s3_key: str | None = None
    page_count: int
    file_size: int
    financial_model_snapshot: dict | None = None
    narrative_snapshot: dict | None = None
